In [1]:
import numpy as np

In [2]:
demet=("a", "b", "c" , 1, 2)
demet

('a', 'b', 'c', 1, 2)

In [3]:
demet[3]

1

In [4]:
demet[2]

'c'

In [5]:
liste1=["a", "b", "c" , 1, 2]
liste1

['a', 'b', 'c', 1, 2]

In [6]:
liste2=["a", "b", "c" , 1, 2,3]

In [7]:
liste1+liste2

['a', 'b', 'c', 1, 2, 'a', 'b', 'c', 1, 2, 3]

In [8]:
dizi1=np.array([1, 2, 3])
dizi1

array([1, 2, 3])

In [9]:
dizi2=np.array([3, 4, 5])

In [10]:
dizi1+dizi2

array([4, 6, 8])

In [11]:
dizi1.dot(dizi2)

26

In [12]:
sözlük1=dict(a=1, b=2, c=3)
sözlük1

{'a': 1, 'b': 2, 'c': 3}

In [13]:
sözlük2={'d': 4, 'e': 5, 'f': 6}

In [14]:
sözlük1.keys()

dict_keys(['a', 'b', 'c'])

In [15]:
sözlük2["d"]

4

In [16]:
import pandas as pd 

In [17]:
df=pd.DataFrame({'d': [4], 'e':[5], 'f': [6]})
df

d  e  f
0  4  5  6

In [18]:
x=np.arange(1,2,0.5)
x

array([1. , 1.5])

In [19]:
y=np.arange(1,5,0.2)
y

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [20]:
a=np.sin(y)
b=np.cos(y)

In [21]:
df2=pd.DataFrame({'sin':a, 'cos':b})
df2.head()

sin       cos
0  0.841471  0.540302
1  0.932039  0.362358
2  0.985450  0.169967
3  0.999574 -0.029200
4  0.973848 -0.227202

In [22]:
df2.tail()

sin       cos
15 -0.756802 -0.653644
16 -0.871576 -0.490261
17 -0.951602 -0.307333
18 -0.993691 -0.112153
19 -0.996165  0.087499

In [25]:
veri=df2[["sin"]]
veri.head()

sin
0  0.841471
1  0.932039
2  0.985450
3  0.999574
4  0.973848

In [26]:
df2[2:4]

sin       cos
2  0.985450  0.169967
3  0.999574 -0.029200

In [28]:
df2.iloc[2:4,[0,]]

sin
2  0.985450
3  0.999574

In [29]:
df2.values

array([[ 0.84147098,  0.54030231],
       [ 0.93203909,  0.36235775],
       [ 0.98544973,  0.16996714],
       [ 0.9995736 , -0.02919952],
       [ 0.97384763, -0.22720209],
       [ 0.90929743, -0.41614684],
       [ 0.8084964 , -0.58850112],
       [ 0.67546318, -0.73739372],
       [ 0.51550137, -0.85688875],
       [ 0.33498815, -0.94222234],
       [ 0.14112001, -0.9899925 ],
       [-0.05837414, -0.99829478],
       [-0.2555411 , -0.96679819],
       [-0.44252044, -0.89675842],
       [-0.61185789, -0.79096771],
       [-0.7568025 , -0.65364362],
       [-0.87157577, -0.49026082],
       [-0.95160207, -0.30733287],
       [-0.993691  , -0.11215253],
       [-0.99616461,  0.08749898]])